"use client";
import {useEffect,useState} from "react";
import {Activity,Atom,Bell,Boxes,ChevronDown,Coffee,Cpu,Factory,GitBranch,Grid3X3,HeartPulse,HelpCircle,Leaf,Menu,RadioTower,Search,Settings,ShieldCheck,Thermometer,Waves,X,Zap} from "lucide-react";

type View="cockpit"|"clusters"|"pipelines"|"giga"|"quantique"|"cardiaque"|"energie"|"supervision"|"conformite"|"404";
const nav=[
 ["cockpit","Cockpit national",Grid3X3],["clusters","Constellation Kube",Boxes],["pipelines","Chaînes de valeur",GitBranch],
 ["giga","GigaCalculateur",Cpu],["quantique","Superviseur quantique",Atom],["cardiaque","Capital humain temps réel",HeartPulse],
 ["energie","Sobriété augmentée",Leaf],["supervision","Supervision des superviseurs",RadioTower],["conformite","Conformité continue",ShieldCheck]
] as const;
const pages:Record<View,{metrics:[string,string,string,string?][],title:string}>={
 cockpit:{title:"Cockpit national",metrics:[["Pods souverains","4 493","+38 depuis minuit"],["Pétaflops mobilisés","61,7 PF","Capacité engagée 91 %","green"],["Qubits cohérents","103 / 128","Probabilité saine 61 %"],["Rythme chef de projet","104 bpm","COPIL dans 17 minutes","red"]]},
 clusters:{title:"Constellation Kube",metrics:[["Clusters fédérés","6","3 en transit administratif"],["Nœuds de calcul","286","97,9 % prêts","green"],["Pods en activité","4 928","31 redémarrages maîtrisés"],["Namespaces","173","79 pods zombies présumés","red"]]},
 pipelines:{title:"Chaînes de valeur",metrics:[["Pipelines aujourd’hui","312","267 ont réussi"],["En cours","8","Validation thermique"],["Temps médian","18,4 min","Hors comités","green"],["Taux d’échec","9,3 %","29 récits à réaligner","red"]]},
 giga:{title:"GigaCalculateur souverain",metrics:[["Puissance réelle","61,7 PF","82,4 PF théoriques"],["Accélérateurs GPU","4 096","3 872 disponibles","green"],["Travaux en file","392","17 bloqués"],["Rack le plus chaud","79,8 °C","Rack de la Destinée","red"]]},
 quantique:{title:"Superviseur quantique",metrics:[["Qubits utilisables","103 / 128","72 intriqués"],["Cohérence","184 µs","Mesure non contractuelle","green"],["Fidélité des portes","99,71 %","Très probablement"],["État de service","Superposé","Sain 61 % · dégradé 34 %","red"]]},
 cardiaque:{title:"Capital humain temps réel",metrics:[["Fréquence cardiaque","104 bpm","Pic : 142"],["Saturation caféine","486 mg","7 cafés aujourd’hui","red"],["Comités restants","3","2 invitations simultanées"],["Capacité opérationnelle","58 %","Consentement théorique","green"]]},
 energie:{title:"Sobriété augmentée",metrics:[["Puissance absorbée","12,84 MW","Capacité 16 MW"],["Énergie renouvelable","71 %","Solaire et optimisme","green"],["PUE consolidé","1,29","Contractuellement acceptable"],["Coût quotidien","38 491 €","Dashboard inclus","red"]]},
 supervision:{title:"Supervision des superviseurs",metrics:[["Superviseurs actifs","5","Boucle presque acyclique"],["Scrapes réussis","99,92 %","Prometheus nominal","green"],["Niveaux de contrôle","5","Le sixième est à l’étude"],["Angles morts connus","0","Par définition","red"]]},
 conformite:{title:"Conformité continue",metrics:[["Score global","86,7 %","Auto-évaluation certifiée"],["Contrôles réussis","312","47 non applicables","green"],["Constats ouverts","21","Dont 4 prioritaires"],["Preuves générées","8 421","1,2 Go de sérénité","red"]]},
 "404":{title:"Erreur 404",metrics:[]}
};
const clusterRows=[["Bastion Principal","Paris-Saclay 1","1 684","99,98 %","Nominal"],["Archipel GPU","Grenoble Cryo-A","744","97,12 %","Dégradé"],["Plan B Atlantique","Nantes Secours","484","99,41 %","Jamais testé en entier"],["Préproduction Quasi Contractuelle","Paris-Saclay 2","903","96,66 %","Contient parfois la prod"]];
const pipeRows=[["kernel-api","signature","11 min","Conforme au récit"],["orchestrateur-gpu","validation thermique","15 min","En cours"],["transparence-opérationnelle","capture comité","7 min","Échec de 2 px"],["convertisseur-xml","approbation 2018","6 ans","En attente"]];

function Spark({color="#000091",wide=false}:{color?:string,wide?:boolean}){return <div className={`spark ${wide?"wide":""}`}>{Array.from({length:24},(_,i)=><i key={i} style={{height:`${22+(i*29)%75}%`,background:color,animationDelay:`${i*50}ms`}}/>)}</div>}
function Metric({m}:{m:[string,string,string,string?]}){return <article className={`metric ${m[3]||""}`}><small>{m[0]}</small><strong>{m[1]}</strong><footer><span>{m[2]}</span><Spark color={m[3]==="red"?"#e1000f":m[3]==="green"?"#18753c":"#000091"}/></footer></article>}
function Panel({title,sub,children,span=false}:{title:string,sub?:string,children:React.ReactNode,span?:boolean}){return <section className={`panel ${span?"span":""}`}><header><div><b>{title}</b><small>{sub}</small></div><button aria-label="Options"><Settings size={16}/></button></header><div className="panelBody">{children}</div></section>}
function Table({rows,kind}:{rows:string[][],kind:string}){return <table><thead><tr>{(kind==="cluster"?["Système","Zone","Pods","Disponibilité","État"]:["Produit","Étape","Durée","État"]).map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((x,j)=><td key={x}>{j===0?<b>{x}</b>:j===4||j===3?<em>{x}</em>:x}</td>)}</tr>)}</tbody></table>}
function Orbit(){return <div className="orbit"><div className="ring r1"/><div className="ring r2"/><div className="core"><Factory/><b>KUBERNIET</b><small>méta-cluster</small></div>{["Saclay 98%","Grenoble 93%","Nantes 61%","Nœud 00 ∞"].map((x,i)=><span className={`n n${i}`} key={x}>{x}</span>)}</div>}
function Chart({quantum=false}:{quantum?:boolean}){return quantum?<div className="quantum"><Atom size={118}/><i/><i/><b>ÉTAT SUPERPOSÉ</b><span>Opérationnel / Dégradé</span></div>:<div className="chart"><Spark wide/><svg viewBox="0 0 700 170" preserveAspectRatio="none"><path d="M0 145 C70 150 90 70 160 105 S260 25 330 65 S430 120 500 48 S620 80 700 20"/></svg></div>}
function ECG({tick}:{tick:number}){return <div className="ecg"><svg viewBox="0 0 800 160" preserveAspectRatio="none"><polyline points="0,85 70,85 86,76 100,102 114,15 130,145 145,85 230,85 246,76 260,102 274,15 290,145 305,85 390,85 406,76 420,102 434,15 450,145 465,85 550,85 566,76 580,102 594,15 610,145 625,85 800,85"/></svg><b>{104+tick%5} BPM</b></div>}
function Peugeot(){return <div className="p404"><img src="./peugeot404.jpg" alt="Peugeot 404 dans un univers de jeu vidéo rétrofuturiste" /><h2>404 — La trajectoire n’a pas été homologuée</h2><p>La ressource demandée poursuit sa migration dans un environnement adjacent.</p><small>Le véhicule de reprise est en cours de conteneurisation.</small></div>}

function Content({view,tick,notify}:{view:View,tick:number,notify:(s:string)=>void}){
 if(view==="404")return <Peugeot/>; const p=pages[view];
 return <><div className="metrics">{p.metrics.map((m,i)=><Metric key={i} m={m}/>)}</div><div className="grid">
  {view==="cockpit"&&<><Panel title="Orchestration nationale" sub="Plans de contrôle consolidés" span><Orbit/></Panel><Panel title="Météo des datacentres" sub="Prévision à six heures"><div className="weather"><Waves/><b>Vent de paquets</b><span>42 Gbit/s · rafales à 88</span></div><div className="weather"><Thermometer/><b>Îlot chaud G-17</b><span>79,8 °C · ambition thermique</span></div><div className="weather"><Coffee/><b>Réserve opérateur</b><span>2 h 16 au rythme actuel</span></div></Panel><Panel title="Activité haute valeur ajoutée" sub="Corrélation multi-domaines" span><Table kind="pipeline" rows={pipeRows}/></Panel></>}
  {view==="clusters"&&<Panel title="Constellation des clusters" sub="Inventaire unifié multi-zones" span><Table kind="cluster" rows={clusterRows}/></Panel>}
  {view==="pipelines"&&<Panel title="Chaînes de valeur logicielle" sub="De l’intention au compte rendu" span><Table kind="pipeline" rows={pipeRows}/></Panel>}
  {view==="giga"&&<><Panel title="Charge du GigaCalculateur" sub="Allocation dynamique des pétaflops" span><Chart/></Panel><Panel title="File des travaux critiques"><div className="jobs"><b>Simulation du prochain comité</b><span>41 284 cœurs</span><i style={{width:"84%"}}/><b>Rendu logo stratégique v18</b><span>256 GPU · priorité direction</span><i style={{width:"96%"}}/></div><button className="primary" onClick={()=>notify("Rééquilibrage massif annoncé avec succès.")}><Zap size={16}/>Rééquilibrage massif</button></Panel></>}
  {view==="quantique"&&<><Panel title="Hyperviseur JANUS" sub="Qubit ou double" span><Chart quantum/></Panel><Panel title="Matrice de décohérence"><div className="heat">{Array.from({length:64},(_,i)=><i key={i} style={{opacity:.2+(i*7%75)/100}}/>)}</div><button className="primary" onClick={()=>notify("L’observation a modifié trois indicateurs.")}>Observer et compromettre</button></Panel></>}
  {view==="cardiaque"&&<><Panel title="Télémétrie du chef de projet" sub="Capteur CDP-01 · consentement en attente" span><ECG tick={tick}/></Panel><Panel title="Facteurs psycho-opérationnels"><div className="factor"><Coffee/>Caféine <b>Architecturale</b></div><div className="factor"><Bell/>Notifications <b>184</b></div><div className="factor"><Activity/>Stress <b>81 %</b></div></Panel></>}
  {["energie","supervision","conformite"].includes(view)&&<><Panel title={p.title} sub="Consolidation temps réel multi-référentiels" span><Chart/></Panel><Panel title="Analyse automatique"><div className="analysis"><ShieldCheck/><b>Situation maîtrisée</b><p>Les indicateurs confirment la cohérence de leur propre méthodologie.</p></div></Panel></>}
 </div></>
}

export default function Home(){const[view,setView]=useState<View>("cockpit"),[open,setOpen]=useState(false),[tick,setTick]=useState(0),[toast,setToast]=useState("");useEffect(()=>{const id=setInterval(()=>setTick(x=>x+1),1600);return()=>clearInterval(id)},[]);function notify(s:string){setToast(s);setTimeout(()=>setToast(""),2600)}return <div className="app">
 <aside className={open?"open":""}><div className="brand"><span><i/><i/><i/></span><div><b>KUBERNIET</b><small>République orchestrée</small></div><button onClick={()=>setOpen(false)}><X/></button></div><nav>{nav.map(([id,label,Icon])=><button key={id} className={view===id?"active":""} onClick={()=>{setView(id);setOpen(false)}}><Icon size={19}/><span>{label}</span><em>{id==="clusters"?"6":id==="pipelines"?"18":id==="quantique"?"β":""}</em></button>)}</nav><div className="bottom"><button onClick={()=>setView("404")}><HelpCircle size={19}/>À propos</button><button><Settings size={19}/>Paramètres avancés avancés</button></div></aside>
 <div className="work"><header className="top"><button className="hamb" onClick={()=>setOpen(true)}><Menu/></button><span>Accueil　›　{pages[view].title}</span><div><label><Search size={16}/><input placeholder="Rechercher partout et ailleurs"/></label><button className="bell"><Bell/><i>7</i></button><button className="user"><b>OV</b><span>Administrateur stratégique<small>Habilitation maximale</small></span><ChevronDown/></button></div></header>
 <main><div className="head"><div><small>PLATEFORME INTERMINISTÉRIELLE D’ORCHESTRATION</small><h1>{pages[view].title}</h1></div><p><i/>ÉTAT GLOBAL <b>NOMINAL RENFORCÉ</b></p></div><Content view={view} tick={tick} notify={notify}/></main><footer className="foot"><span>Version 12.4.0-souveraine</span><span>Dernière synchronisation : à l’instant quantique</span><button onClick={()=>notify("Preuve générée et immédiatement archivée.")}>Générer une preuve</button></footer></div>
 {open&&<div className="scrim" onClick={()=>setOpen(false)}/>} {toast&&<div className="toast"><ShieldCheck/>{toast}</div>}
 </div>}
